name: 'Run and check test'
description: ''
inputs:
  test_names:
    description: 'Names of the tests'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./action-setup
    - id: run-and-check-test
      env:
        INPUT_TEST_NAMES: ${{ inputs.test_names }}
      run: |
        set -e
        [[ -z "$INPUT_TEST_NAMES" ]] && echo "variable INPUT_TEST_NAMES is empty. exit" && exit 1
        artifact_name=$(echo "results_${INPUT_TEST_NAMES// /_}" | sed "s/[^a-zA-Z']/_/g")
        echo "artifact=$artifact_name" >> "$GITHUB_OUTPUT"
        echo "path=**$YC_LT_OUTPUT_DIR**" >> "$GITHUB_OUTPUT"
        automation/test.sh $INPUT_TEST_NAMES
      shell: bash
    - name: upload-artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-and-check-test.outputs.artifact }}
        path: ${{ steps.run-and-check-test.outputs.path }}
