name: 'Check test'
description: ''
outputs:
  check_results:
    description: ""
    value: ${{ steps.run-checks.outputs.check_results }}
runs:
  using: "composite"
  steps:
    - uses: ./action-setup
    - id: run-checks
      run: |
        echo "GOT RUN_TEST_ID $RUN_TEST_ID"
        echo "GOT RUN_TEST_DIR $RUN_TEST_DIR"
        artifact_name=$(echo "results_${RUN_TEST_DIR// /_}" | sed "s/[^a-zA-Z']/_/g")
        echo "artifact=$artifact_name" >> "$GITHUB_OUTPUT"
        echo "path=**$YC_LT_OUTPUT_DIR/$RUN_TEST_ID**" >> "$GITHUB_OUTPUT"
        rc=0
        if ! check_results=$(automation/test_check.sh --id $RUN_TEST_ID --dir $RUN_TEST_DIR -o "$YC_LT_OUTPUT_DIR/$RUN_TEST_ID"); then rc=1; fi
        echo "CHECK RESULTS:"
        echo "$check_results"
        mkdir -p "$YC_LT_OUTPUT_DIR/$RUN_TEST_ID"
        echo "$check_results" > "$YC_LT_OUTPUT_DIR/$RUN_TEST_ID/check_result.txt"
        ls -la "$YC_LT_OUTPUT_DIR/$RUN_TEST_ID"
        echo "### CHECK RESULTS" >> $GITHUB_STEP_SUMMARY
        echo -e "\`\`\` $check_results \n \`\`\` " >> $GITHUB_STEP_SUMMARY
        exit ${rc}
      shell: bash
    - name: upload-artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.run-checks.outputs.artifact }}
        path: ${{ steps.run-checks.outputs.path }}
