name: 'Run test'
description: ''
runs:
  using: "composite"
  steps:
    - uses: ./yc-setup
    - name: delete agents
      run: |
        set -e
        _impl/agent_delete.sh --labels "workflow=${WORKFLOW_ID}"
      shell: bash