name: 'Create agent'
description: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./action-setup
    - name: create agent
      run: |
        set -e
        automation/agent_create.sh --count $AGENTS_COUNT \
          --description "CI agent" \
          --labels "workflow=${WORKFLOW_ID}"
      shell: bash


