name: yc-load-testing-ci
run-name: yc-load-testing-ci
on: [ push ]
env:
  YC_LT_AGENT_NAME_PREFIX: "ci-lt-agent"
  YC_LT_AGENT_LABELS: ""
  YC_LT_FOLDER_ID: b1g5mqk0rkb81u1kf2d4
  YC_LT_AUTHORIZED_KEY_JSON: ${{ secrets.YC_LOADTESTING_CI_AUTHORIZED_KEY_JSON }}
  YC_LT_AGENT_SA_ID: ${{ secrets.SERVICE_ACCOUNT_ID }}
  YC_LT_AGENT_CORES: 2
  YC_LT_AGENT_MEMORY: "2G"
  YC_LT_AGENT_ZONE: ru-central1-b
  YC_LT_AGENT_IPV4_ADDRESS: "auto"
  YC_LT_AGENT_SUBNET_ID: ${{ secrets.SUBNET_ID }}
  YC_LT_AGENT_SUBNET_NAME: ""
  YC_LT_AGENT_SECURITY_GROUP_IDS: ${{ secrets.SECURITY_GROUP_IDS }}
  YC_LT_AGENT_CREATE_TIMEOUT: "720"

  YC_LT_OUTPUT_DIR: ".loadtesting-agents-output"
  YC_LT_VERBOSE: 1
  YC_LT_TARGET: ${{ secrets.YC_LT_TARGET }}
  YC_LT_SKIP_TEST_CHECK: "0"
  YC_LT_TEST_AGENT_FILTER: "labels.workflow = '${{github.run_id}}'"
  YC_LT_TEST_EXTRA_DESCRIPTION: "GitHub Actions workflow - ${{github.run_id}}"
  YC_LT_TEST_EXTRA_LABELS: ""
  AGENTS_COUNT: 2

  WORKFLOW_ID: ${{github.run_id}}
jobs:
  create-agents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./action-create-agent

  run-test-const:
    needs: [ create-agents ]
    concurrency:
      group: loadtesting
    runs-on: ubuntu-latest
    outputs:
      output_test_id: ${{ steps.run.outputs.test_id }}
      output_tests_dir: ${{ steps.run.outputs.test_dir }}
    steps:
      - uses: actions/checkout@v4
      - id: run
        uses: ./action-run-test
        with:
          test_dir: "sample-tests/root-const"
        env:
          YC_LT_DATA_BUCKET: ${{ secrets.YC_LT_DATA_BUCKET }}

  check-const:
    needs: [ run-test-const ]
    runs-on: ubuntu-latest
    outputs:
      output_check_results: ${{ steps.check.outputs.check_results }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        uses: ./action-check-test
        env:
          RUN_TEST_ID:
            ${{needs.run-test-const.outputs.output_test_id}}
          RUN_TEST_DIR:
            ${{needs.run-test-const.outputs.output_tests_dir}}

  run-and-check:
    needs: [ run-test-const ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: run-and-check
        uses: ./action-run-and-check
        with:
          test_names: "sample-tests/root-const sample-tests/root-imbalance"

  delete-agents:
    needs: [ check-const, run-and-check ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./action-delete-agents


