core:
  # enable to get more logs on agent
  debug: false 

autostop:
  enabled: true
  package: yandextank.plugins.Autostop
  autostop:
    # force stop if:

    # 15m min passed
    - limit(15m)
    # for 5s, 10% of requests failed due to generator overload
    - total_net(777, 10%, 5s)
    # for 5s, 50% of net requests failed
    - total_http(0, 50%, 5s)
    # for 20s, each second, 20% of http requests failed
    - negative_http(2xx, 20%, 20s)
    # for 10s, each second, average response time exceeds 500ms
    - time(500, 10s)

pandora:
  enabled: true
  package: yandextank.plugins.Pandora
  config_content:
    pools:
      - id: HTTP
        discard_overflow: true
        gun:
          type: http
          target: ''
          ssl: false
        ammo:
          type: uri
          uris:
            - '/ root'
        startup:
          type: once
          times: 1000
        rps:
          - duration: 10m
            type: line
            from: 1
            to: 15000

telegraf:
  enabled: true
  package: yandextank.plugins.Telegraf
  config:
    hosts:
      localhost:
    metrics:
      cpu:
      mem:
      diskio:
      net:
      netstat:
      system:
      kernel:
