name: Generate README.md
run-name: generate-readme
on:
  - push
  - workflow_dispatch
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: pndurette/gh-actions-auto-docs@v1
        with:
          action_yaml_file: ./agents-create/action.yml
          marker_start: '<!--doc-begin-agents-create-->'
          marker_end: '<!--doc-end-agents-create-->'
